slcp/src/accounts/urls.py
from django.conf.urls import patterns, include, url

from . import views

urlpatterns = patterns(
    '',
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
#    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),
        name='password-reset-confirm'),
)

slcp/src/slcp/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
from . import views

urlpatterns = patterns(
    '',
    url(r'^$', views.dashboard, name='home'),
#   url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^create_brand/$', views.create_brand, name='create_brand'),
    url(r'^list_brands/$', views.list_brands, name='list_brands'),
    url(r'^create_account/$', views.create_account, name='create_account'),
    url(r'^update_account/(?P<account_id>\d+)', views.create_account, name='update_account'),
    url(r'^list_accounts/$', views.list_accounts, name='list_accounts'),
    url(r'^report_invoices/$', views.report_invoices, name='report_invoices'),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),

    #auth
    (r'^accounts/',  include(accounts.urls)),
    (r'^profile/',  include(profiles.urls)),
)

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

slcp/src/accounts/models.py
from django.db import models

# Create your models here.

slcp/src/accounts/forms.py
from __future__ import unicode_literals
from django.contrib.auth import forms as authforms
from django import forms
from django.conf import settings
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions
#from authtools import forms as authtoolsforms
from django.contrib.auth import forms as authforms
from django.core.urlresolvers import reverse


class LoginForm(authforms.AuthenticationForm):
    remember_me = forms.BooleanField(required=False, initial=False)

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
      # self.fields["username"].widget.input_type = "email"  # ugly hack

        self.helper.layout = Layout(
            Field('username', placeholder="Enter Username", autofocus=""),
            Field('password', placeholder="Enter Password"),
            HTML('<a href="{}">Forgot Password?</a>'.format(
                reverse("accounts:password-reset"))),
            Field('remember_me'),
            Submit('sign_in', 'Log in',
                   css_class="btn btn-lg btn-primary btn-block"),
            )

    def confirm_login_allowed(self, user):
        super(LoginForm, self).confirm_login_allowed(user)
        remember_me = self.cleaned_data.get('remember_me')
        if remember_me is True:
            ONE_MONTH = 30*24*60*60
            expiry = getattr(settings, "KEEP_LOGGED_DURATION", ONE_MONTH)
            self.request.session.set_expiry(expiry)


class SignupForm(authforms.UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        #self.fields["email"].widget.input_type = "email"  # ugly hack

        self.helper.layout = Layout(
         #   Field('email', placeholder="Enter UserName", autofocus=""),
            Field('username', placeholder="Enter Full Name"),
            Field('password1', placeholder="Enter Password"),
            Field('password2', placeholder="Re-enter Password"),
            Submit('sign_up', 'Sign up', css_class="btn-warning"),
            )


class PasswordChangeForm(authforms.PasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super(PasswordChangeForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()

        self.helper.layout = Layout(
            Field('old_password', placeholder="Enter old password",
                  autofocus=""),
            Field('new_password1', placeholder="Enter new password"),
            Field('new_password2', placeholder="Enter new password (again)"),
            Submit('pass_change', 'Change Password', css_class="btn-warning"),
            )


class PasswordResetForm(authforms.PasswordResetForm):

    def __init__(self, *args, **kwargs):
        super(PasswordResetForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()

        self.helper.layout = Layout(
            Field('email', placeholder="Enter email",
                  autofocus=""),
            Submit('pass_reset', 'Reset Password', css_class="btn-warning"),
            )


class SetPasswordForm(authforms.SetPasswordForm):
    def __init__(self, *args, **kwargs):
        super(SetPasswordForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()

        self.helper.layout = Layout(
            Field('new_password1', placeholder="Enter new password",
                  autofocus=""),
            Field('new_password2', placeholder="Enter new password (again)"),
            Submit('pass_change', 'Change Password', css_class="btn-warning"),
            )

slcp/src/accounts/views.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse_lazy
from django.views import generic
from django.contrib.auth import get_user_model
from django.contrib import auth
from django.contrib import messages
from authtools import views as authviews
from braces import views as bracesviews
from . import forms
import logging
User = get_user_model()

log = logging.getLogger('SLCP')

class LoginView(bracesviews.AnonymousRequiredMixin,
                authviews.LoginView):
    url = reverse_lazy('slcp:dashboard')
    template_name = "accounts/login.html"
    form_class = forms.LoginForm


class LogoutView(authviews.LogoutView):
    url = reverse_lazy('home')

    def get(self, *args, **kwargs):
        log.info("User (%s) logged out" % self.request.user)
        return super(LogoutView, self).get(*args, **kwargs)


class SignUpView(bracesviews.AnonymousRequiredMixin,
                 bracesviews.FormValidMessageMixin,
                 generic.CreateView):
    form_class = forms.SignupForm
    model = User
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('home')
    form_valid_message = "You're signed up!"

    def form_valid(self, form):
        r = super(SignUpView, self).form_valid(form)
        username = form.cleaned_data["email"]
        password = form.cleaned_data["password1"]
        user = auth.authenticate(email=username, password=password)
        auth.login(self.request, user)
        return r


class PasswordChangeView(authviews.PasswordChangeView):
    form_class = forms.PasswordChangeForm
    template_name = 'accounts/password-change.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.save()
        messages.success(self.request,
                         "Your password was changed, "
                         "hence you have been logged out. Please relogin")
        return super(PasswordChangeView, self).form_valid(form)


class PasswordResetView(authviews.PasswordResetView):
    form_class = forms.PasswordResetForm
    template_name = 'accounts/password-reset.html'
    success_url = reverse_lazy('accounts:password-reset-done')
    subject_template_name = 'accounts/emails/password-reset-subject.txt'
    email_template_name = 'accounts/emails/password-reset-email.html'


class PasswordResetDoneView(authviews.PasswordResetDoneView):
    template_name = 'accounts/password-reset-done.html'


class PasswordResetConfirmView(authviews.PasswordResetConfirmAndLoginView):
    template_name = 'accounts/password-reset-confirm.html'
    form_class = forms.SetPasswordForm

slcp/src/accounts/templates/accounts/auth_base.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block navbar %}
{% endblock %}

{% comment %}
{% block container %}
    <div class="container form-box">
      <div class="text-center">
        <h2>{% block form_heading %}{% endblock %}</h2>
      </div>
      {% block form %}
      {% endblock %}
    </div>
{% endblock container %}

{% endcomment %}

{% block main %}
  <div class="text-center">
        <h2>{% block form_heading %}{% endblock %}</h2>
  </div>
  {% block form %}
  {% endblock %}
{% endblock main %}

slcp/src/accounts/templates/accounts/login.html
{% extends "accounts/auth_base.html" %}
{% load crispy_forms_tags %}

{% block navigation %}
{% endblock %}


{% block main %}
<body>

    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">{% block form_heading %}Please Sign In {% endblock %}</h3>
                    </div>
                    <div class="panel-body">
                        {% block form %}
                          {% crispy form %}
                        {% endblock form %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

slcp/src/accounts/templates/accounts/password-change.html
{% extends "accounts/auth_base.html" %}

{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Password Change{% endblock %}

{% block form_heading %}Password Change{% endblock %}

{% block form %}
    <div class="col-sm-4">
        {% crispy form %}
    </div>
{% endblock form %}

slcp/src/accounts/templates/accounts/password-reset-confirm.html
{% extends "accounts/login.html" %}

{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Password Change{% endblock %}

{% block form_heading %}Password Change{% endblock %}

{% block form %}
  {% crispy form %}
{% endblock form %}

slcp/src/accounts/templates/accounts/password-reset-done.html
{% extends "accounts/login.html" %}

{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Password Reset Done{% endblock %}

{% block form_heading %}Password Reset Email Sent{% endblock %}

{% block form %}
<div class="form-message">
  <p>
    Please check your mail. You would have recieved a password reset mail from us.
  </p>
</div>
{% endblock form %}

slcp/src/accounts/templates/accounts/password-reset.html
{% extends "accounts/login.html" %}

{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Password Reset{% endblock %}

{% block form_heading %}Password Reset{% endblock %}

{% block form %}
  {% crispy form %}
{% endblock form %}

slcp/src/accounts/templates/accounts/signup.html
{% extends "accounts/auth_base.html" %}

{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Sign Up{% endblock %}

{% block form_heading %}Signing Up is Free{% endblock %}

{% block form %}
  {% crispy form %}

  <div class="form-message">
    <p>
      Already signed up? <a href="{% url 'accounts:login' %}">Log in</a>.
    </p>
  </div>
{% endblock form %}